import {
  Profile1,
  Profile10,
  Profile11,
  Profile12,
  Profile13,
  Profile14,
  Profile15,
  Profile16,
  Profile2,
  Profile3,
  Profile4,
  Profile5,
  Profile6,
  Profile7,
  Profile8,
  Profile9,
  Thumb1,
  Thumb10,
  Thumb11,
  Thumb12,
  Thumb13,
  Thumb14,
  Thumb15,
  Thumb16,
  Thumb2,
  Thumb3,
  Thumb4,
  Thumb5,
  Thumb6,
  Thumb7,
  Thumb8,
  Thumb9,
} from "./Assets/AssetsPaths";
let videosList = [
  // thumb, prof, title, published, channel, views
  {
    id: 1,
    thumb: Thumb1,
    prof: Profile1,
    title: "Master Complete Html and Css in 6 hours!",
    channel: "Super Simple dev",
    views: "3.4M",
    published: "1 year",
    time: "6:00:00",
  },
  {
    id: 2,
    thumb: Thumb2,
    prof: Profile2,
    title:
      "Master the MERN tech stack by building a Full stack Booking App projects ",
    channel: "Mern Master",
    views: "3k",
    published: "3 years",
    time: "4:13:25",
  },
  {
    id: 3,
    thumb: Thumb3,
    prof: Profile3,
    title: "Take Me to Church: A Musical Journey",
    channel: "Music Enthusiast",
    views: "2.7M",
    published: "8 months",
    time: "4:30",
  },
  {
    id: 4,
    thumb: Thumb4,
    prof: Profile4,
    title: "React Course: Building Modern Web Applications",
    channel: "React Mastermind",
    views: "1.8M",
    published: "6 months",
    time: "10:00:00",
  },
  {
    id: 5,
    thumb: Thumb5,
    prof: Profile5,
    title: "Arduino Course: Learn Electronics and Programming",
    channel: "Arduino Guru",
    views: "4.2M",
    published: "1 year",
    time: "7:45:25",
  },
  {
    id: 6,
    thumb: Thumb6,
    prof: Profile6,
    title: "Pure Code Experience: Mastering Programming Techniques",
    channel: "Code Maestro",
    views: "2.3M",
    published: "9 months",
    time: "5:15",
  },
  {
    id: 7,
    thumb: Thumb7,
    prof: Profile7,
    title: "Image Generation AI: Creating Art with Neural Networks",
    channel: "AI Artist",
    views: "1.5M",
    published: "11 months",
    time: "3:45",
  },
  {
    id: 8,
    thumb: Thumb8,
    prof: Profile8,
    title: "Unity Course: Building Games and Virtual Worlds",
    channel: "Unity Wizard",
    views: "2.0M",
    published: "10 months",
    time: "6:30",
  },
  {
    id: 9,
    thumb: Thumb9,
    prof: Profile9,
    title: "Attack on Titans: Exploring the Epic Anime Universe",
    channel: "Anime Enthusiast",
    views: "3.8M",
    published: "1 year and 6 months",
    time: "8:20",
  },
  {
    id: 10,
    thumb: Thumb10,
    prof: Profile10,
    title: "3D Web Development: Building Immersive Online Experiences",
    channel: "Web 3D Architect",
    views: "1.2M",
    published: "7 months",
    time: "9:15",
  },
  {
    id: 11,
    thumb: Thumb11,
    prof: Profile11,
    title:
      "DSA Masterclass: A Comprehensive Guide to Data Structures and Algorithms",
    channel: "Algorithm Guru",
    views: "2.5M",
    published: "1 year and 3 months",
    time: "11:30",
  },
  {
    id: 12,
    thumb: Thumb12,
    prof: Profile12,
    title: "I Want to Eat Your Pancreas: X Let me down slowly edit",
    channel: "Anime Film Buff",
    views: "1.6M",
    published: "1 year and 9 months",
    time: "7:00",
  },
  {
    id: 13,
    thumb: Thumb13,
    prof: Profile13,
    title: "Ordinary Person Song: Leo vijay",
    channel: "Music Lover",
    views: "2M",
    published: "3 months",
    time: "4:45",
  },
  {
    id: 14,
    thumb: Thumb14,
    prof: Profile14,
    title: "Thomas Shelby: The Mastermind Behind the Peaky Blinders",
    channel: "Peaky Blinders Fan",
    views: "1.5M",
    published: "5 months",
    time: "8:30",
  },
  {
    id: 15,
    thumb: Thumb15,
    prof: Profile15,
    title: "Shinunoga E-Wa: Mesmerizing Melody from the East",
    channel: "Music Explorer",
    views: "1.2M",
    published: "6 months",
    time: "4:30",
  },
  {
    id: 16,
    thumb: Thumb16,
    prof: Profile16,
    title: "Korean Chili Chicken: Spicy and Delicious Recipe",
    channel: "Cooking Enthusiast",
    views: "900K",
    published: "5 months",
    time: "12:00",
  },
];
export { videosList };
